application: twcl-ck
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /.*
  script: helloworld.app


- url: /ipynbs
  static_dir: ipynbs


libraries:
- name: webapp2
  version: "2.5.2"
